# Copyright 2020 Oprea Olivia Maria-Magdalena 323CA <opreaolivia73@gmail.com>
# In colaborare cu echipa de pc care a facut laburile din care am luat codul :)

CFLAGS = -Wall -g

all: server subscriber

# Compileaza server.c
server: server.c -lm

# Compileaza subscriber.c
subscriber: subscriber.c

clean:
	rm -f server subscriber
